horseshop/horseshop/urls.py
from django.contrib import admin
from django.urls import path, include
import product.views as product
from horseshop.settings import DEBUG

urlpatterns = [
    path('', product.index, name='home'),
    path('product/', include('product.urls', namespace='product')),
    path('shopauth/', include('shopauth.urls', namespace='shopauth')),
    path('admin/', admin.site.urls),
]
# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if DEBUG:
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

horseshop/product/urls.py
from django.urls import path

import product.views as product

app_name = 'product'

urlpatterns = [
    path('detail/<int:pk>/', product.ProductDetailView.as_view(), name='detail'),
    path('list/', product.ProductsListView.as_view(), name='list'),
]

horseshop/shopauth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

import shopauth.views as shopauth

app_name = 'shopauth'

urlpatterns = [
    path('register/',shopauth.ShopUserCreateView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

horseshop/category/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=32, unique=True, null=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return f"{self.name}"


class Subcategory(models.Model):
    name = models.CharField(max_length=32, unique=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return f"{self.name}"

horseshop/order/models.py
from django.db import models

# Create your models here.
# Create your models here.

class Customer(models.Model):
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    phone = models.CharField(max_length=32, default='')
    email = models.EmailField(max_length=64, default='')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Order(models.Model):
    CREATED = 'C'
    ACTIVE = 'A'
    FINISHED = 'F'
    STATUS = [
        (CREATED, 'Created'),
        (ACTIVE, 'Active'),
        (FINISHED, 'Finished')
    ]
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_created=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_created=True, auto_now_add=False)
    status = models.CharField(max_length=1, choices=STATUS, default='C')
    comment = models.TextField(blank=True)

    def __str__(self):
        return f"order {self.pk} status {self.status}"

horseshop/product/models.py
from django.db import models

# Create your models here.
from category.models import Subcategory
from order.models import Order


# Create your models here.
class Manufacturer(models.Model):
    name = models.CharField(max_length=64)
    country = models.CharField(max_length=64)
    phone = models.CharField(max_length=64)
    email = models.EmailField()
    site = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name} {self.country}"


class ProductProperty(models.Model):
    BLACK = 'BK'
    WHITE = 'WT'
    BLUE = 'BL'
    BROWN = 'BR'
    RED = 'RD'
    COLORS = [
        (BLACK, 'Black'),
        (WHITE, 'White'),
        (BROWN, 'Brown'),
        (RED, 'Red')
    ]
    CHILD = 'C'
    MALE = 'M'
    FEMALE = 'F'
    GENDER = [
        (CHILD, 'Child'),
        (MALE, 'Male'),
        (FEMALE, 'Female')
    ]
    SIZES = [(38, '38'),
             (40, '40'),
             (42, '42'),
             (44, '44'),
             (46, '46')
             ]
    manufactured = models.IntegerField(default=0)
    color = models.CharField(max_length=2, choices=COLORS, default='BK')
    size = models.IntegerField(choices=SIZES, default=38)
    gender = models.CharField(max_length=1, choices=GENDER, default='M')

    def __str__(self):
        return f"color:{self.color}, size:{self.size}, gender:{self.gender}"


class Product(models.Model):
    name = models.CharField(max_length=64)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE, null=True)
    curr_price = models.DecimalField(max_digits=10, decimal_places=2)
    curr_count = models.IntegerField()
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, null=True)
    property = models.OneToOneField('product.ProductProperty', on_delete=models.CASCADE, null=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return f"{self.name}"


class ProductInOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    count = models.IntegerField()
    description = models.TextField(blank=True)

    def __str__(self):
        return f"product{self.product.name} in order{self.order.primary_key}"

horseshop/shopauth/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class ShopUser(AbstractUser):
    phone = models.CharField(max_length=64,blank=True)

horseshop/shopauth/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import ShopUser


class ShopUserCreateForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'email', 'password1', 'password2')

horseshop/category/views.py
# Create your views here.

horseshop/order/views.py
# Create your views here.

horseshop/product/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import DetailView, ListView
from product.models import Product

def index(request):
    context = {
        'title': 'Home page'
    }
    return render(request, 'product/index.html', context)


class ProductDetailView(DetailView):
    model = Product

class ProductsListView(ListView):
    model = Product

horseshop/shopauth/views.py
from django.views.generic import CreateView

from .forms import ShopUserCreateForm
from .models import ShopUser


class ShopUserCreateView(CreateView):
    model = ShopUser
    success_url = '/'
    form_class = ShopUserCreateForm

horseshop/product/templates/product/index.html
{% extends 'base.html' %}
{% block title %} {{title}}
{% endblock %}
{% block main_content %}
    <p> Welcome to our shop main page!
        Our aim is to provide the very best products for you and your horse, not only at the lowest prices but with the
        back up of excellent customer service and after sales service.
    </p>

{% endblock %}

horseshop/product/templates/product/product_detail.html
{% extends 'base.html' %}

{% block title %} Product detail
{% endblock %}
{% block main_content %}
    <p>
        {{ object }}
    </p>
{% endblock %}

horseshop/product/templates/product/product_list.html
{% extends 'base.html' %}
{% block title %} Product list
{% endblock %}
{% block main_content %}
    <ul>
        {% for object in object_list %}
            <li><a href="{% url 'product:detail' object.pk %}">{{ object }}</a></li>
            {% empty %}
            <li>No products yet.</li>
        {% endfor %}
    </ul>
{% endblock %}
{% block product_list %}
{% endblock %}

horseshop/shopauth/templates/shopauth/shopuser_form.html
{% extends 'base.html' %}
{% block title %} Registration
{% endblock %}
{% block main_content %}
    <div class="user-creation-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="save">
        </form>
    </div>
{% endblock %}

{% block menu %}
{% endblock %}

horseshop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" href="{% static 'product/css/bootstrap.css' %}">

    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>

</head>

<body>

{% block main_content %}

{% endblock %}

{% block menu %}
    <ul>
        <li><a href="{% url 'shopauth:register' %}">user registration</a></li>
        <li>
            {% if user.is_anonymous %}
                <a href="{% url 'shopauth:login' %}">login</a>
            {% else %}
                <a href="{% url 'shopauth:logout' %}">logout</a>
                <br>
                <br>
{% block product_list %}
                <a href="{% url 'product:list' %}">to products list </a>
 {% endblock %}
            {% endif %}
        </li>
    </ul>
{% endblock %}

</body>
</html>